name: DEPLOY

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Construction de l'image Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/butify:latest ./docker

      - name: Publication de l'image Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/butify:latest