name: DEPLOY

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t butify:latest ./docker

      - name: Sauvegarde de l'image Docker
        run: docker save butify:latest -o butify.tar

      - name: Stocker l'image Docker pour le job suivant
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: butify.tar
          retention-days: 1

  commit-image-to-stable:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Télécharger l'image Docker sauvegardée
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Basculer sur la branche stable
        run: git checkout stable

      - name: Déplacer le fichier dans le bon emplacement
        run: mv butify.tar butify.tar

      - name: Commit et push uniquement l'image Docker
        run: |
          git add butify.tar
          git commit -m "Mise à jour de l'image Docker depuis main [skip ci]"
          git push origin stable

