name: DEPLOY

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t butify:latest ./docker

      - name: Sauvegarde de l'image Docker
        run: docker save butify:latest -o butify.tar

      - name: Stockage de l'image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: butify.tar
          retention-days: 1

  commit-to-stable:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installation de Git LFS
        run: |
          git lfs install
          git lfs track "*.tar"

      - name: Changement sur la branche stable
        run: | 
          git checkout stable
          rm butify.tar

      - name: Téléchargement de l'image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Commit et push de l'image
        run: |
          git add butify.tar
          git commit -m "Update stable docker image"
          git push origin stable

